/**
 * The tray icon is the app's only surface while the control window is hidden, which is the
 * normal state once "start with Windows" is on. It therefore has to carry enough status to be
 * useful on its own — the icon colour and tooltip say what the connector is doing without
 * opening anything.
 *
 * Everything here degrades instead of failing. Tray support is not guaranteed on Linux (it
 * needs a StatusNotifier host), and the icon set is generated by `npm run icon` rather than
 * checked in, so both the icons and the `Tray` itself may be unavailable. A missing tray costs
 * the user the background affordance; it must never cost them the app.
 */

import { app, Menu, nativeImage, Tray, type NativeImage } from 'electron';
import { existsSync } from 'node:fs';
import path from 'node:path';
import type { ConnectionState } from '../../shared/types.js';
import { logWarn } from '../../main/logger.js';

export type TrayIndicator = 'idle' | 'pending' | 'connected' | 'error';

export interface TrayController {
  show: () => void;
  connect: () => void;
  disconnect: () => void;
  openLogFile: () => void;
  quit: () => void;
}

export function indicatorFor(state: ConnectionState): TrayIndicator {
  switch (state) {
    case 'connected':
      return 'connected';
    case 'starting-server':
    case 'connecting-tunnel':
      return 'pending';
    case 'offline':
    case 'auth-failed':
    case 'tunnel-unavailable':
      return 'error';
    default:
      return 'idle';
  }
}

/**
 * Generated icons live beside the other build artefacts in development and are copied into
 * `resources/tray` when packaged. The plain app icon is the last resort so a tray still
 * appears — colourless, but present — if `npm run icon` has not been run in a checkout.
 */
function iconCandidates(indicator: TrayIndicator): string[] {
  const packaged = path.join(process.resourcesPath, 'tray');
  const local = path.join(app.getAppPath(), 'build', 'tray');
  const base = app.isPackaged ? [packaged, local] : [local, packaged];
  return [
    ...base.map((directory) => path.join(directory, `${indicator}.png`)),
    path.join(process.resourcesPath, 'runtime-icon.png'),
    path.join(app.getAppPath(), 'build', 'icon.png')
  ];
}

function loadIcon(indicator: TrayIndicator): NativeImage | null {
  for (const candidate of iconCandidates(indicator)) {
    if (!existsSync(candidate)) continue;
    // createFromPath picks up a sibling @2x file on its own, which is what keeps the tray
    // sharp on a scaled Windows display.
    const image = nativeImage.createFromPath(candidate);
    if (!image.isEmpty()) return image;
  }
  return null;
}

const iconCache = new Map<TrayIndicator, NativeImage | null>();

function icon(indicator: TrayIndicator): NativeImage | null {
  if (!iconCache.has(indicator)) iconCache.set(indicator, loadIcon(indicator));
  return iconCache.get(indicator) ?? null;
}

let tray: Tray | null = null;
let controller: TrayController | null = null;
let current: { indicator: TrayIndicator; detail: string; connected: boolean; connectorName: string } = {
  indicator: 'idle',
  detail: 'Disconnected.',
  connected: false,
  connectorName: 'localMCP-chat'
};

function rebuildMenu(): void {
  if (!tray || !controller) return;
  const owner = controller;
  tray.setContextMenu(
    Menu.buildFromTemplate([
      { label: `${current.connectorName} — ${current.detail}`, enabled: false },
      { type: 'separator' },
      { label: 'Open control window', click: () => owner.show() },
      current.connected
        ? { label: 'Disconnect', click: () => owner.disconnect() }
        : { label: 'Connect', click: () => owner.connect() },
      { type: 'separator' },
      { label: 'Open log file', click: () => owner.openLogFile() },
      { type: 'separator' },
      { label: `Quit ${current.connectorName}`, click: () => owner.quit() }
    ])
  );
}

/** Returns true when a tray was created; false means the platform or icons were unavailable. */
export function createTray(owner: TrayController): boolean {
  if (tray) return true;
  const image = icon(current.indicator);
  if (!image) {
    logWarn('tray icons are unavailable; run "npm run icon" to generate them');
    return false;
  }
  try {
    tray = new Tray(image);
  } catch (error) {
    // Common on a Linux desktop with no StatusNotifier host. Not worth failing startup over.
    logWarn(`tray unavailable: ${error instanceof Error ? error.message : String(error)}`);
    tray = null;
    return false;
  }
  controller = owner;
  tray.setToolTip(`${current.connectorName} — ${current.detail}`);
  tray.on('click', () => owner.show());
  tray.on('double-click', () => owner.show());
  rebuildMenu();
  return true;
}

export function updateTray(state: ConnectionState, detail: string, connectorName = 'localMCP-chat'): void {
  const indicator = indicatorFor(state);
  const connected = state !== 'disconnected';
  if (indicator === current.indicator && detail === current.detail && connected === current.connected && connectorName === current.connectorName) return;
  current = { indicator, detail, connected, connectorName };
  if (!tray) return;
  const image = icon(indicator);
  if (image) tray.setImage(image);
  tray.setToolTip(`${connectorName} — ${detail}`);
  rebuildMenu();
}

export function destroyTray(): void {
  tray?.destroy();
  tray = null;
  controller = null;
}

export function hasTray(): boolean {
  return tray !== null;
}
